from fastapi import APIRouter

router = APIRouter(prefix="/api/ml", tags=["Registry"])


@router.get("/models")
def get_model_registry():
  return {
      "total_models": 12,
      "production_ready_count": 12,
      "models": [
          ### TABULAR MODELS
          {
              "model_id": "heart_disease",
              "model_name": "Heart Disease Risk Classifier",
              "modality": "tabular",
              "task": "Binary Classification",
              "framework": ["Scikit-Learn", "XGBoost", "Random Forest"],
              "version": "1.0.0",
              "production_ready": True,
              "endpoints": {
                  "unified": "/api/ml/diagnose/symptoms-based",
                  "individual": "/api/ml/predict/heart-disease",
              },
              "fields": [
                  {
                      "name": "age",
                      "type": "integer",
                      "required": True,
                      "description": "Patient age in years",
                  },
                  {
                      "name": "sex",
                      "type": "integer",
                      "options": [{"1": "Male"}, {"0": "Female"}],
                      "required": True,
                  },
                  {
                      "name": "cp",
                      "type": "integer",
                      "description": "Chest pain type (0-3)",
                      "required": True,
                  },
                  {
                      "name": "trestbps",
                      "type": "integer",
                      "description": "Resting blood pressure (mm Hg)",
                      "required": False,
                  },
                  {
                      "name": "chol",
                      "type": "integer",
                      "description": "Serum cholesterol (mg/dl)",
                      "required": False,
                  },
                  {
                      "name": "fbs",
                      "type": "integer",
                      "description": "Fasting blood sugar > 120 mg/dl (1/0)",
                      "required": False,
                  },
                  {
                      "name": "restecg",
                      "type": "integer",
                      "description": "Resting ECG (0-2)",
                      "required": False,
                  },
                  {
                      "name": "thalach",
                      "type": "integer",
                      "description": "Maximum heart rate achieved",
                      "required": False,
                  },
                  {
                      "name": "exang",
                      "type": "integer",
                      "description": "Exercise induced angina (1/0)",
                      "required": False,
                  },
                  {
                      "name": "oldpeak",
                      "type": "float",
                      "description": "ST depression induced by exercise",
                      "required": False,
                  },
                  {
                      "name": "slope",
                      "type": "integer",
                      "description": "Peak exercise ST slope (0-2)",
                      "required": False,
                  },
                  {
                      "name": "ca",
                      "type": "integer",
                      "description": "Major vessels colored (0-4)",
                      "required": False,
                  },
                  {
                      "name": "thal",
                      "type": "integer",
                      "description": "Thalassemia status (1-3)",
                      "required": False,
                  },
              ],
          },
          {
              "model_id": "diabetes",
              "model_name": "Diabetes Prediction Model",
              "modality": "tabular",
              "task": "Binary Classification",
              "framework": ["Scikit-Learn", "XGBoost", "Random Forest"],
              "version": "1.0.0",
              "production_ready": True,
              "endpoints": {
                  "unified": "/api/ml/diagnose/symptoms-based",
                  "individual": "/api/ml/predict/diabetes",
              },
              "fields": [
                  {"name": "pregnancies", "type": "integer", "required": False},
                  {
                      "name": "glucose",
                      "type": "float",
                      "description": "Plasma glucose concentration",
                      "required": True,
                  },
                  {
                      "name": "blood_pressure",
                      "type": "float",
                      "description": "Diastolic blood pressure",
                      "required": False,
                  },
                  {
                      "name": "skin_thickness",
                      "type": "float",
                      "required": False,
                  },
                  {"name": "insulin", "type": "float", "required": False},
                  {
                      "name": "bmi",
                      "type": "float",
                      "description": "Body Mass Index",
                      "required": True,
                  },
                  {
                      "name": "diabetes_pedigree_function",
                      "type": "float",
                      "required": False,
                  },
                  {"name": "age", "type": "integer", "required": True},
              ],
          },
          {
              "model_id": "hypertension",
              "model_name": "Hypertension Screening Model",
              "modality": "tabular",
              "task": "Binary Classification",
              "framework": ["Scikit-Learn", "XGBoost", "Random Forest"],
              "version": "1.0.0",
              "production_ready": True,
              "endpoints": {
                  "unified": "/api/ml/diagnose/symptoms-based",
                  "individual": "/api/ml/predict/hypertension",
              },
              "fields": [
                  {"name": "Age", "type": "integer", "required": True},
                  {
                      "name": "Sex",
                      "type": "integer",
                      "options": [{"1": "Male"}, {"0": "Female"}],
                      "required": True,
                  },
                  {
                      "name": "HighChol",
                      "type": "integer",
                      "options": [{"1": "Yes"}, {"0": "No"}],
                      "required": False,
                  },
                  {"name": "BMI", "type": "float", "required": True},
              ],
          },
          {
              "model_id": "anaemia",
              "model_name": "Anaemia Diagnostic Model",
              "modality": "tabular",
              "task": "Binary Classification",
              "framework": ["Scikit-Learn", "XGBoost", "Random Forest"],
              "version": "1.0.0",
              "production_ready": True,
              "endpoints": {
                  "unified": "/api/ml/diagnose/symptoms-based",
                  "individual": "/api/ml/predict/anaemia",
              },
              "fields": [
                  {
                      "name": "gender",
                      "type": "integer",
                      "options": [{"1": "Male"}, {"0": "Female"}],
                      "required": True,
                  },
                  {
                      "name": "mch",
                      "type": "float",
                      "description": "Mean Corpuscular Hemoglobin",
                      "required": True,
                  },
                  {
                      "name": "mchc",
                      "type": "float",
                      "description": "Mean Corpuscular Hemoglobin Conc.",
                      "required": True,
                  },
                  {
                      "name": "mcv",
                      "type": "float",
                      "description": "Mean Corpuscular Volume",
                      "required": True,
                  },
              ],
          },
          {
              "model_id": "hepatitis_b",
              "model_name": "Hepatitis B & Hepatic Classifier",
              "modality": "tabular",
              "task": "Binary Classification",
              "framework": ["Scikit-Learn", "XGBoost", "Random Forest"],
              "version": "1.0.0",
              "production_ready": True,
              "endpoints": {
                  "unified": "/api/ml/diagnose/symptoms-based",
                  "individual": "/api/ml/predict/hepatitis-b",
              },
              "fields": [
                  {"name": "age", "type": "integer", "required": True},
                  {
                      "name": "sex",
                      "type": "integer",
                      "options": [{"1": "Male"}, {"0": "Female"}],
                      "required": True,
                  },
                  {
                      "name": "bilirubin",
                      "type": "float",
                      "description": "Total Bilirubin (mg/dL)",
                      "required": True,
                  },
                  {
                      "name": "alk_phosphate",
                      "type": "float",
                      "description": "Alkaline Phosphatase (IU/L)",
                      "required": False,
                  },
                  {
                      "name": "spleen_palpable",
                      "type": "integer",
                      "options": [{"1": "Yes"}, {"0": "No"}],
                      "required": False,
                  },
                  {
                      "name": "spiders",
                      "type": "integer",
                      "options": [{"1": "Yes"}, {"0": "No"}],
                      "required": False,
                  },
                  {
                      "name": "varices",
                      "type": "integer",
                      "options": [{"1": "Yes"}, {"0": "No"}],
                      "required": False,
                  },
              ],
          },
          ### IMAGE MODELS
          {
              "model_id": "pneumonia",
              "model_name": "Chest X-Ray Pneumonia Detector",
              "modality": "image",
              "task": "Image Classification",
              "framework": ["PyTorch", "Torchvision"],
              "version": "1.0.0",
              "production_ready": True,
              "endpoints": {
                  "unified": "/api/ml/diagnose/image-based",
                  "individual": "/api/ml/predict/image",
              },
              "image_type_value": "xray",
              "inputs": [
                  {
                      "name": "file",
                      "type": "file",
                      "accept": [".jpg", ".jpeg", ".png"],
                      "required": True,
                  },
                  {
                      "name": "image_type",
                      "type": "string",
                      "value": "xray",
                      "required": True,
                  },
                  {
                      "name": "clinical_notes",
                      "type": "string",
                      "required": False,
                  },
              ],
          },
          {
              "model_id": "covid19",
              "model_name": "Chest X-Ray COVID-19 Detector",
              "modality": "image",
              "task": "Image Classification",
              "framework": ["PyTorch", "Torchvision"],
              "version": "1.0.0",
              "production_ready": True,
              "endpoints": {
                  "unified": "/api/ml/diagnose/image-based",
                  "individual": "/api/ml/predict/covid19",
              },
              "image_type_value": "xray",
              "inputs": [
                  {
                      "name": "file",
                      "type": "file",
                      "accept": [".jpg", ".jpeg", ".png"],
                      "required": True,
                  },
                  {
                      "name": "image_type",
                      "type": "string",
                      "value": "xray",
                      "required": True,
                  },
                  {
                      "name": "clinical_notes",
                      "type": "string",
                      "required": False,
                  },
              ],
          },
          {
              "model_id": "tuberculosis",
              "model_name": "Tuberculosis X-Ray Classifier",
              "modality": "image",
              "task": "Image Classification",
              "framework": ["PyTorch", "Torchvision"],
              "version": "1.0.0",
              "production_ready": True,
              "endpoints": {
                  "unified": "/api/ml/diagnose/image-based",
                  "individual": "/api/ml/predict/tuberculosis",
              },
              "image_type_value": "xray",
              "inputs": [
                  {
                      "name": "file",
                      "type": "file",
                      "accept": [".jpg", ".jpeg", ".png"],
                      "required": True,
                  },
                  {
                      "name": "image_type",
                      "type": "string",
                      "value": "xray",
                      "required": True,
                  },
                  {
                      "name": "clinical_notes",
                      "type": "string",
                      "required": False,
                  },
              ],
          },
          {
              "model_id": "malaria",
              "model_name": "Malaria Blood Smear Cell Classifier",
              "modality": "image",
              "task": "Microscopy Image Classification",
              "framework": ["PyTorch", "Torchvision"],
              "version": "1.0.0",
              "production_ready": True,
              "endpoints": {
                  "unified": "/api/ml/diagnose/image-based",
                  "individual": "/api/ml/predict/malaria",
              },
              "image_type_value": "blood_smear",
              "inputs": [
                  {
                      "name": "file",
                      "type": "file",
                      "accept": [".jpg", ".jpeg", ".png"],
                      "required": True,
                  },
                  {
                      "name": "image_type",
                      "type": "string",
                      "value": "blood_smear",
                      "required": True,
                  },
                  {
                      "name": "clinical_notes",
                      "type": "string",
                      "required": False,
                  },
              ],
          },
          {
              "model_id": "skin_conditions",
              "model_name": "Dermatological Multi-Condition Classifier",
              "modality": "image",
              "task": "Multi-class Classification",
              "framework": ["PyTorch", "Torchvision"],
              "version": "1.0.0",
              "production_ready": True,
              "endpoints": {
                  "unified": "/api/ml/diagnose/image-based",
                  "individual": "/api/ml/predict/skin-conditions",
              },
              "image_type_value": "skin",
              "inputs": [
                  {
                      "name": "file",
                      "type": "file",
                      "accept": [".jpg", ".jpeg", ".png"],
                      "required": True,
                  },
                  {
                      "name": "image_type",
                      "type": "string",
                      "value": "skin",
                      "required": True,
                  },
                  {
                      "name": "clinical_notes",
                      "type": "string",
                      "required": False,
                  },
              ],
          },
          {
              "model_id": "skin_cancer",
              "model_name": "Skin Cancer / Melanoma Classifier",
              "modality": "image",
              "task": "Binary/Lesion Classification",
              "framework": ["PyTorch", "Torchvision"],
              "version": "1.0.0",
              "production_ready": True,
              "endpoints": {
                  "unified": "/api/ml/diagnose/image-based",
                  "individual": "/api/ml/predict/skin-cancer",
              },
              "image_type_value": "skin",
              "inputs": [
                  {
                      "name": "file",
                      "type": "file",
                      "accept": [".jpg", ".jpeg", ".png"],
                      "required": True,
                  },
                  {
                      "name": "image_type",
                      "type": "string",
                      "value": "skin",
                      "required": True,
                  },
                  {
                      "name": "clinical_notes",
                      "type": "string",
                      "required": False,
                  },
              ],
          },
          {
              "model_id": "breast_cancer",
              "model_name": "Breast Cancer Screening Classifier",
              "modality": "image",
              "task": "Binary Classification",
              "framework": ["PyTorch", "Torchvision"],
              "version": "1.0.0",
              "production_ready": True,
              "endpoints": {
                  "unified": "/api/ml/diagnose/image-based",
                  "individual": "/api/ml/predict/breast-cancer",
              },
              "image_type_value": "histology",
              "inputs": [
                  {
                      "name": "file",
                      "type": "file",
                      "accept": [".jpg", ".jpeg", ".png"],
                      "required": True,
                  },
                  {
                      "name": "image_type",
                      "type": "string",
                      "value": "histology",
                      "required": True,
                  },
                  {
                      "name": "clinical_notes",
                      "type": "string",
                      "required": False,
                  },
              ],
          },
      ],
  }